### ISSUE TITLE
Improve condition for api ping

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#1]
Improve the server fingerprinting when checking if the api is reachable

Currently the condition checks only that the server returns statusCode 401. Additionaly we could check that the server returns the `www-authenticate` header and that it is set to `Basic realm="balloon"`

https://github.com/gyselroth/balloon-client-desktop/blob/master/app/ui/startup/browser.js#L103

**Comment by raffis** [comment]
Probably balloon v2 will provide an endpoint for unauthenticated requests were you can check if it is a valid balloon server.

**Comment by pixtron** [comment]
Change in balloon server for api/v1 will be released with balloon@v2.2.0-beta1

**Comment by raffis** [comment]
> Change in balloon server for api/v1 will be released with balloon@v2.2.0-beta1

Using /api/v2 for the ping.
