### ISSUE TITLE
Feedback occasionally sends corrupt zip

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#107]
#### Description
**Is**:
Feedback sends corrupt zip. (Can be extracted anyway using jar)

**Should**:
Valid zip file.

#### balloon desktop version
0.2.0

#### Your client operating system
Windows 10

**Comment by pixtron** [comment]
Looks like a duplicate of #105

**Comment by pixtron** [comment]
There is a regression introduced to #105. If fsInfo fails, and snapshot has not yet been appended to archive, the archiver will fail with `Error: append: queue closed`
