### ISSUE TITLE
Cannot use localhost as server url

### ISSUE THREAD

**Issue by johnsardine** [gyselroth/balloon-client-desktop#11]
When running the server locally, I set the port to `8181` and can correctly run and access the web client, however the desktop client does not accept `https://localhost:8181/` as a valid url

![screenshot 2017-09-04 23 38 53](https://user-images.githubusercontent.com/679335/30039531-46439eec-91ca-11e7-8a17-641aa9fd2450.png)
<img width="1279" alt="screenshot 2017-09-04 23 39 09" src="https://user-images.githubusercontent.com/679335/30039533-494e0208-91ca-11e7-8f7a-530bb8f10227.png">

**Comment by raffis** [comment]
probably going to remove regex uri check https://github.com/gyselroth/balloon-client-desktop/blob/master/app/ui/startup/browser.js#L82 and only check connectivity with a ping request
