### ISSUE TITLE
context menu is not in the top right corner

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#112]
#### Description
**Is**:
OS X, notebook plus external monitor (external monitor is the primary screen).
The context menu opens on the primary one but in the middle attached on the left side.

**Should**:
Open normally in the top right corner.

#### balloon desktop version
0.2.1

#### Your client operating system
OS X

**Comment by pixtron** [comment]
Should be fixed with pixtron/electron-traywindow-positioner#9.
