### ISSUE TITLE
Ignore all shares by default 

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#116]
#### Description
**Is**:
All shares/share references get synced.

**Should**:
Disable shares in selective sync and the user must enable those manually.

#### balloon desktop version
0.2.1

**Comment by pixtron** [comment]
If an instance exists and a new share appears in delta it should be added to ignored nodes

**Comment by pixtron** [comment]
Implemented with https://github.com/gyselroth/balloon-node-sync/commit/7c99b02f61655d2955adf89b153dc9b405cfd378
