### ISSUE TITLE
The whole cloud can get delerted if the Balloon folder gets moved/removed

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#122]
#### Description
**Is**:
1. Sync Cloud
2. Removed the Balloon folder /home/user/Balloon
3. Nodes get deleted in the cloud

**Should**:
Abort sync if running, clean database, resync entire cloud.

#### balloon desktop version
v0.2.3

#### Your client operating system
Linux Mint 18

**Comment by pixtron** [comment]
See #121

**Comment by pixtron** [comment]
the behavior is reproducible under the following conditions:

1.) balloonDir exists when full sync is started
2.) balloonDir is deleted before (complete data loss) or while (partial data loss) [findDeletedNodes](https://github.com/gyselroth/balloon-node-sync/blob/master/lib/delta/local-delta.js#L234) runs.

**Comment by pixtron** [comment]
The issue has been resolved with 4311cae. If sync module is used in another application, the application has to handle this case.
