### ISSUE TITLE
Ask admin privileges for fsutil calls on windows

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#135]
#### Description
**Is**:
fsutil requires admin privileges. On clients where the app does not run with admin privileges the fsutil calls throw an error and the fs information for the error report is not generated
```
{  
   "cmd":"fsutil fsinfo volumeinfo C:",
   "err":{  
      "stack":"Error: Command failed: fsutil fsinfo volumeinfo C:\n\n at ChildProcess.exithandler (child_process.js:287:12)\n at emitTwo (events.js:126:13)\n at ChildProcess.emit (events.js:214:7)\n at maybeClose (internal/child_process.js:925:16)\n at Socket.stream.socket.on (internal/child_process.js:346:11)\n at emitOne (events.js:116:13)\n at Socket.emit (events.js:211:7)\n at Pipe._handle.close [as _onclose] (net.js:554:12)",
      "message":"Command failed: fsutil fsinfo volumeinfo C:\n",
      "killed":false,
      "code":1,
      "signal":null,
      "cmd":"fsutil fsinfo volumeinfo C:"
   }
}
```
**Should**:
Eventually we can circumvent this problem by asking the user for admin privileges [2], and run the fsutil command in a subprocess 

#### balloon desktop version
0.2.3

#### Your client operating system
Windows

#### Filesystem (If known)
N/A

#### balloon server version (If known)
N/A

[1] https://answers.microsoft.com/en-us/windows/forum/windows_7-security/need-administrative-privileges/7f229c52-2d04-474e-8e70-1deaebf18cf3
[2] https://www.npmjs.com/package/electron-sudo

**Comment by raffis** [comment]
fixed by #146
