### ISSUE TITLE
Replace fsinfo with output from systeminformation package

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#146]
#### Description
Replace all fsinfo output in feedback with output from [stysteminformation](https://www.npmjs.com/package/systeminformation)

The module might make #144 obsolete.
This should make make #135 obsolete.

#### balloon desktop version
0.2.4

#### Your client operating system
N/A

#### Filesystem (If known)
N/A

#### balloon server version (If known)
N/A

**Comment by pixtron** [comment]
@raffis can you check if the module has the required information to close #144?

**Comment by raffis** [comment]
@pixtron No, not all. We still need the information.
But we can just include all env variables (all os), so those needed will be included.
So basically the information from systeminformation and all env variables.

```
{ version: '3.49.2',
  system: 
   { manufacturer: '',
     model: '',
     version: '',
     serial: '',
     uuid: '-',
     sku: '-' },
  bios: { vendor: '', version: '', releaseDate: '', revision: '' },
  baseboard: 
   { manufacturer: '',
     model: '',
     version: '',
     serial: '-',
     assetTag: '-' },
  os: 
   { platform: 'linux',
     distro: 'LinuxMint',
     release: '17.3',
     codename: 'rosa',
     kernel: '3.19.0-32-generic',
     arch: 'x64',
     hostname: 'test-ThinkPad-T450s',
     codepage: [Function: trim],
     logofile: 'mint',
     serial: '',
     build: '' },
  uuid: { os: 'e0ad0e8ad9343a5c99be7d5255ed7456' },

```

**Comment by raffis** [comment]
+ process.env
