### ISSUE TITLE
Corrupt Feedback

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#175]
since v1.0.0-rc1 the feedbacks often are corrupted, and the spinner seems to spin forever.

**Comment by pixtron** [comment]
The problem occurs on mac and for all of the corrupt reports `report/metadata.json` is missing. 
Probably the method `getMetaData` never returns and meanwhile the server is running into a timeout.

Eventually related to: https://github.com/sebhildebrandt/systeminformation/issues/189

**Comment by raffis** [comment]
Fixed in v1.0.0-rc2
