### ISSUE TITLE
An update is ready to install, helper program

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#192]
#### Describe the bug
This popup is displayed way more than once on osx. Somehow the update probably does not get installed. What does lead to this problem?

#### To Reproduce
Installed v1.0.0 => update available for v1.1.0

#### Environment
 - desktop client version: v1.0.0 -> v1.1.0
 - balloon server version: [e.g. v2.4.2]
 - client os: [e.g. Linux Mint 19.2]
 - client cpu architecture: [e.g. amd64]
 - filesystem: [e.g. ntfs (Where the balloon folder is located)]

**Comment by raffis** [comment]
Probably related to the update check and the fact that the user did not trigger the update.

**Comment by pixtron** [comment]
Closing this issue as the fixes have been published with v1.2.0
