### ISSUE TITLE
Open balloon the 2nd time does not open the balloon folder

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#202]
#### Describe the bug
Users report that (randomly?) a (double) click on the balloon task tray or via start menu does not open the balloon folder in the windows explorer. 

#### To Reproduce
It is not clear when this happens, maybe a race condition or it only works once.

#### Expected behavior
Always open the balloon folder in the explorer.

#### Environment
 - desktop client version: v1.1.1
 - client os: Windows 10

**Comment by pixtron** [comment]
Can't reproduce the issue.

**Comment by raffis** [comment]
This is probably some kind of race condition. This can certainly happen but may be difficult to reproduce.

**Comment by pixtron** [comment]
The method `showBalloonDir` checked if the client was launched with the flag `--hidden` (autolaunch), if so it silently failed and did not open the balloonDir.

With e954b3d the call to showBalloonDir was moved from the second instance (which never gets launched with `--hidden` to the primary instance. Therefore if the client was launched with `--hidden` the balloon Dir would never open.

Remove the check for `--hidden` flag completely as it is not necessary anymore (in earlier versions `showBalloonDir` was called on every start.
