### ISSUE TITLE
Install latest release (including pre-releases) does not install the latest release

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#208]
#### Describe the bug
Install pre-releases does not necessarily install the latest release.

#### To Reproduce
1. Install v1.0.0
2. Enable pre-releases
3. App updates to v1.1.1. (latest release on github)

#### Expected behavior
v1.2.0-alpha4 should have been installed.

**Comment by pixtron** [comment]
Probably this issue: electron-userland/electron-builder/issues/1625

**Comment by raffis** [comment]
Sorting api is still sorted by publish date: 
```
curl https://api.github.com/repos/gyselroth/balloon-client-desktop/releases
```

stuff like `?sort=tag_name` does not work and there is also no documentation regarding sorting.


This probably has to be fixed in electron-updated to loop the last n releases and do a manual sort.
(test with latest electron-updater first tough).

https://github.com/electron-userland/electron-builder/blob/v29.30.0/packages/electron-updater/src/providers/GitHubProvider.ts#L35

**Comment by raffis** [comment]
Not sure where this went wrong. I checked the elctron-updater code. It just fetches the github releases feed as xml atom and grabs the latest github release. So just using the order provided by github. I create a couple of test releases following semantic versioning and the order is correct: https://github.com/gyselroth/balloon-client-desktop-update-testing/releases

However checking the order of balloon desktop releases it seems like there are some releases in the wrong order. For example  1.2.0-alpha4 is before v1.1.1 which is wrong.
