### ISSUE TITLE
Temp folder does not get cleaned up

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#218]
#### Describe the bug
The feedback contains no data.
Probably because the .balloon folder is too big.

The other issue is that the .balloon folder may have loads of files in temp which not seemed to get cleaned up even tough there should have been a fix in v1.2. 

#### To Reproduce
?

#### Expected behavior
* Files in temp folder should get cleaned up.
* Working zip file in feedback. (Does temp get zipped as well?)

#### Environment
 - desktop client version: v1.2.0
 - balloon server version: 2.6.7
 - client os: OS X

**Comment by pixtron** [comment]
Cleaning up temp files seems to have worked in v1.2.0 as temp folder in current instance (instance-4) has a combined size of 0B.

```
  0B	/Users/.../.balloon/temp
  0B	/Users/.../.balloon/instance-4/temp
 26M	/Users/.../.balloon/instance-2/temp
607M	/Users/.../.balloon/instance-1/temp
```

**Comment by pixtron** [comment]
temp folders are excluded while creating the zip:

https://github.com/gyselroth/balloon-client-desktop/blob/3d434124489fd1315520b14f9df439e8463f32f8/app/ui/feedback/controller.js#L172-L175

But the size of the zipped report seems to be still bigger then the allowed limit in redmine (nodes.db of instance-4 is already ~14MB).

**Comment by pixtron** [comment]
In the logs the http request for sending the feedback returns status code 200.

**Comment by pixtron** [comment]
After our discussion, closing this issue. Problem seems to be the proxy between client and redmine.
