### ISSUE TITLE
Linux cleanup after uninstall

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#226]
#### Describe the bug

After deinstallation of the app the following should be cleaned up:
 
* Remove Nautilus bookmarks
* Remove bur file association
* Autostart entries?

#### To Reproduce
Unistall balloon.

#### Environment
 - desktop client version: 1.2.1
 - client os: Linux

#### Additional context
See #32

**Comment by raffis** [comment]
Same here, see #227 
We're going the path with proper documentation on how to uninstall the client. It makes no sense to implement this in an uninstaller. At least not yet. If this will change we can reopen the issue.
