### ISSUE TITLE
Uninstaller for OSX

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#227]
#### Describe the bug

The uninstaller should clean up the following:

* Remove bookmarks
* Autostart entries

As the deinstallation on OSX happens by just moving the app to the trash, there is no "uninstall" event. The only option would be to create an uninstall executable.

#### To Reproduce
"uninstall" balloon

#### Environment
 - desktop client version: 1.2.1
 - client os: OSX

#### Additional context
See #32

**Comment by pixtron** [comment]
Eventually a "How to uninstall" article would help the user to remove all data: https://help.dropbox.com/en-en/installs-integrations/desktop/uninstall-dropbox

**Comment by raffis** [comment]
We're going the path with proper documentation on how to uninstall the client. It makes no sense to implement this in an uninstaller. At least not yet. If this will change we can reopen the issue.
