### ISSUE TITLE
offline event does not trigger in some circumstances

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#39]
#### Description
**Is**:
offline event does not trigger in some circumstances. Could be some other interfaces.

**Should**:
Triggers if no inet connection.

#### balloon desktop version
0.0.33

#### Your client operating system
Linux Mint 17

**Comment by raffis** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

**Comment by pixtron** [comment]
If sync ends with a network error, the online state is now set to "offline" and the client tries to "reconnect" every 5s. 
see commit #317eb62

**Comment by raffis** [comment]
fixed with 0.0.34
