### ISSUE TITLE
Possibility to move balloon sync folder afterwards

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#46]
#### Description
**Is**:
For now it is only possible to set the balloon folder during first start.

**Should**:
Move the balloon folder afterwards. (Settings)

**Comment by raffis** [comment]
If a file is locked by the os (windows) and can not be moved, we may catch that and copy the file instead.

**Comment by pixtron** [comment]
The custom dir should be per instance, if an instance has no data dir configured default dir should be used.
If a new instance is created (aka new user logs in) default dir should be used. But it should be possible to change Dir via "extended settings".
