### ISSUE TITLE
Check for updates should display a notification that a new version has been found

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#59]
#### Description
**Is**:
A loader is showed up til a new version has been downloaded.

**Should**:
Show a notification that a new version has been found which is currently downloading.

#### balloon desktop version
0.0.35

#### Your client operating system
Windows 10

**Comment by pixtron** [comment]
Requires the introduction of a new global App state `updateDownloading` as `updateAvailable ` is only set, when update has been fully downloaded.

Also see #74
