### ISSUE TITLE
about check for new version tells now newer version available if main is actually downloading the latest release in the background

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#74]
#### Description
**Is**:
No newer release available.

**Should**:
Show message that the latest release is downloading.

#### balloon desktop version
0.0.38

#### Your client operating system
Windows 10

**Comment by pixtron** [comment]
Should not update tray with `update-not-available`

https://github.com/gyselroth/balloon-client-desktop/blob/0016f6d136042f8b0b69b7343d049bad80939cc8/app/lib/auto-update/controller.js#L77-L85
