### ISSUE TITLE
new state initial sync?

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#76]
#### Description
**Is**:
Connecting a cloud with thousands of nodes takes several minutes until something happens in the sync folder.
tray icon stays normal and mentions "Your balloon is synchronized".

(In the background the delta gets fetched which can take several minutes.) More performance with bigger limit?

**Should**:
The tray should actually be spinning and state must be either "sync initial state" or just "syncing".
Either tray should be spinning during initial sync or if a sync takes more thank x seconds.

#### balloon desktop version
0.0.38

**Comment by pixtron** [comment]
TODO's

1.) when remote delta has > 1 node, show spinner in tray
2.) when local delta has > 1 changes, show spinner in tray
3.) Changes from error queue should not show spinner in tray

**Comment by pixtron** [comment]
Resolved with 0016f6d tray animation starts as soon as a sync starts
