### ISSUE TITLE
If feedback ends in an error a message occurs but the loader is still visible and the form can not be resent

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#77]
#### Description
**Is**:
Long feedbacks end in an error. An error occurs but the loader is still visible.

**Should**:
* Add text limit for feedback
* Hide loader after an error occurred
* Form should be resend-able

#### balloon desktop version
0.0.39

#### Your client operating system
Linux Mint

**Comment by pixtron** [comment]
> - Hide loader after an error occurred
> - Form should be resend-able

Fixed with: c6220f4

**Comment by pixtron** [comment]
> - Add text limit for feedback

@raffis what is the text limit?

**Comment by pixtron** [comment]
Closing this issue in favor of #217
