### ISSUE TITLE
endless sync error loop Is**: `Error: \"toString()\" failed\n    at Buffer.toString (buffer.js:503

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#85]
#### Description
**Is**:
`Error: \"toString()\" failed\n    at Buffer.toString (buffer.js:503:11)\n    at tryToString (fs.js:445:15)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)","level":"error","timestamp":"2017-11-24T07:25:05.123Z"}`

**Should**:
fix Error: \"toString()\" failed\n

#### balloon desktop version
0.0.39

**Comment by pixtron** [comment]
Seems to be remoteDeltaLogDb which is > 268MB 
see: https://github.com/nodejs/node/issues/2767

**Comment by raffis** [comment]
fixed by https://github.com/gyselroth/balloon-node-sync/commit/e99b4312dac3710e42dcdd67d645815c5b41d00c
